Tue Apr 18 21:07:42 2023
Linux-5.19.0-38-generic-x86_64-with-glibc2.35
Ren'Py 8.0.3.22090809
 

Bootstrap to the start of init.init took 0.30s
Early init took 0.00s
Loader init took 0.02s
Loading error handling took 0.11s
Loading script took 0.32s
Loading save slot metadata. took 0.02s
Loading persistent took 0.00s
Faled to initialize steam: OSError('/home/techno/Downloads/renpy/renpy-8.0.3-sdk/lib/py3-linux-x86_64/libsteam_api.so: cannot open shared object file: No such file or directory')
Running init code took 0.15s
Loading analysis data took 0.08s
Analyze and compile ATL took 0.01s
Index archives took 0.00s
Dump and make backups. took 0.24s
Cleaning cache took 0.00s
Making clean stores took 0.00s
Initial gc. took 0.06s
DPI scale factor: 1.000000
Creating interface object took 0.00s
Cleaning stores took 0.00s
Init translation took 0.13s
Build styles took 0.02s
Load screen analysis took 0.11s
Analyze screens took 0.00s
Save screen analysis took 0.00s
Prepare screens took 0.25s
Save pyanalysis. took 0.00s
Save bytecode. took 0.00s
Running _start took 0.00s
Performance test:
Interface start took 0.40s

Initializing gl2 renderer:
primary display bounds: (0, 0, 1366, 768)
swap interval: 1 frames
Windowed mode.
Vendor: "b'Intel'"
Renderer: b'Mesa Intel(R) HD Graphics (BYT)'
Version: b'4.2 (Compatibility Profile) Mesa 22.2.5'
Display Info: None
Screen sizes: virtual=(1280, 720) physical=(1184, 666) drawable=(1184, 666)
Could not open 'cache/shaders.txt':
Maximum texture size: 4096x4096
Screen sizes: virtual=(1280, 720) physical=(663, 719) drawable=(663, 719)
Could not open 'cache/shaders.txt':
Maximum texture size: 4096x4096
Cleaning stores took 0.00s
Init translation took 0.00s
Build styles took 0.02s
Load screen analysis took 0.13s
Analyze screens took 0.00s
Prepare screens took 0.00s
Running _start took 0.01s
